services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.136.0
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
      - ./artifacts/perf:/artifacts/perf
