// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/tasuku43/vivi/server/gitreview"
	"github.com/tasuku43/vivi/server/workspace"
)

type AddCommentInput struct {
	Body   string             `json:"body"`
	Actor  *CommentActorInput `json:"actor,omitempty"`
	Author *string            `json:"author,omitempty"`
	Source *CommentSource     `json:"source,omitempty"`
}

type ChangeReviewSummary struct {
	Available bool                `json:"available"`
	Reason    *string             `json:"reason,omitempty"`
	Changes   []*gitreview.Change `json:"changes"`
}

type Comment struct {
	ID            string             `json:"id"`
	ThreadID      *string            `json:"threadId,omitempty"`
	Path          string             `json:"path"`
	ViewerKind    string             `json:"viewerKind"`
	ReviewBatchID *string            `json:"reviewBatchId,omitempty"`
	Anchor        map[string]any     `json:"anchor"`
	DiffAnchor    *DiffCommentAnchor `json:"diffAnchor,omitempty"`
	Body          string             `json:"body"`
	CreatedBy     *CommentActor      `json:"createdBy"`
	Author        *string            `json:"author,omitempty"`
	Source        CommentSource      `json:"source"`
	Status        CommentStatus      `json:"status"`
	CreatedAt     string             `json:"createdAt"`
	UpdatedAt     string             `json:"updatedAt"`
	ResolvedAt    *string            `json:"resolvedAt,omitempty"`
	ArchivedAt    *string            `json:"archivedAt,omitempty"`
}

type CommentActor struct {
	ID          string           `json:"id"`
	Kind        CommentActorKind `json:"kind"`
	DisplayName *string          `json:"displayName,omitempty"`
}

type CommentActorInput struct {
	ID          string           `json:"id"`
	Kind        CommentActorKind `json:"kind"`
	DisplayName *string          `json:"displayName,omitempty"`
}

type CommentExport struct {
	Format      CommentExportFormat `json:"format"`
	ContentType string              `json:"contentType"`
	Content     string              `json:"content"`
}

type CommentInput struct {
	ThreadID   *string            `json:"threadId,omitempty"`
	Path       string             `json:"path"`
	ViewerKind *string            `json:"viewerKind,omitempty"`
	Anchor     map[string]any     `json:"anchor"`
	Body       string             `json:"body"`
	Actor      *CommentActorInput `json:"actor,omitempty"`
	Author     *string            `json:"author,omitempty"`
	Source     *CommentSource     `json:"source,omitempty"`
	Status     *CommentStatus     `json:"status,omitempty"`
}

type CommentMeta struct {
	Statuses      []CommentStatus             `json:"statuses"`
	Surfaces      []string                    `json:"surfaces"`
	ExportFormats []string                    `json:"exportFormats"`
	ActorKinds    []CommentActorKind          `json:"actorKinds"`
	ActivityTypes []CommentThreadActivityType `json:"activityTypes"`
}

type CommentThread struct {
	ID            string             `json:"id"`
	Path          string             `json:"path"`
	Status        CommentStatus      `json:"status"`
	ReviewBatchID *string            `json:"reviewBatchId,omitempty"`
	Anchor        map[string]any     `json:"anchor,omitempty"`
	DiffAnchor    *DiffCommentAnchor `json:"diffAnchor,omitempty"`
	UpdatedAt     *string            `json:"updatedAt,omitempty"`
	CreatedAt     string             `json:"createdAt"`
	ResolvedAt    *string            `json:"resolvedAt,omitempty"`
	ArchivedAt    *string            `json:"archivedAt,omitempty"`
	Comments      []*Comment         `json:"comments"`
}

type CommentThreadActivityEvent struct {
	ID             string                    `json:"id"`
	ThreadID       string                    `json:"threadId"`
	Type           CommentThreadActivityType `json:"type"`
	Actor          *CommentActor             `json:"actor"`
	CommentID      *string                   `json:"commentId,omitempty"`
	PreviousStatus *CommentStatus            `json:"previousStatus,omitempty"`
	Status         *CommentStatus            `json:"status,omitempty"`
	ClientEventID  *string                   `json:"clientEventId,omitempty"`
	LeaseExpiresAt *string                   `json:"leaseExpiresAt,omitempty"`
	CreatedAt      string                    `json:"createdAt"`
}

type CommentThreadClaim struct {
	Thread   *CommentThread              `json:"thread"`
	Activity *CommentThreadActivityEvent `json:"activity"`
}

type CommentThreadClaimInput struct {
	Actor         *CommentActorInput `json:"actor"`
	ClientEventID *string            `json:"clientEventId,omitempty"`
	LeaseSeconds  *int               `json:"leaseSeconds,omitempty"`
}

type CommentThreadClaimRelease struct {
	Thread   *CommentThread              `json:"thread"`
	Activity *CommentThreadActivityEvent `json:"activity"`
}

type CommentThreadClaimReleaseInput struct {
	Actor         *CommentActorInput `json:"actor"`
	ClientEventID *string            `json:"clientEventId,omitempty"`
}

type CommentThreadUpdateInput struct {
	Status CommentStatus      `json:"status"`
	Actor  *CommentActorInput `json:"actor,omitempty"`
}

type CommentUpdateInput struct {
	Body   *string            `json:"body,omitempty"`
	Status *CommentStatus     `json:"status,omitempty"`
	Actor  *CommentActorInput `json:"actor,omitempty"`
}

// Stable location of a comment in a unified diff. Line numbers are 1-based.
type DiffCommentAnchor struct {
	Path         string   `json:"path"`
	Base         string   `json:"base"`
	Ref          string   `json:"ref"`
	HunkID       string   `json:"hunkId"`
	Side         DiffSide `json:"side"`
	OldLineStart *int     `json:"oldLineStart,omitempty"`
	OldLineEnd   *int     `json:"oldLineEnd,omitempty"`
	NewLineStart *int     `json:"newLineStart,omitempty"`
	NewLineEnd   *int     `json:"newLineEnd,omitempty"`
	DiffHash     *string  `json:"diffHash,omitempty"`
	FileHash     *string  `json:"fileHash,omitempty"`
}

type DraftReviewComment struct {
	ID         string             `json:"id"`
	ThreadID   *string            `json:"threadId,omitempty"`
	Path       string             `json:"path"`
	ViewerKind string             `json:"viewerKind"`
	Anchor     map[string]any     `json:"anchor"`
	DiffAnchor *DiffCommentAnchor `json:"diffAnchor,omitempty"`
	Body       string             `json:"body"`
	CreatedBy  *CommentActor      `json:"createdBy"`
	Author     *string            `json:"author,omitempty"`
	Source     CommentSource      `json:"source"`
	CreatedAt  string             `json:"createdAt"`
	UpdatedAt  string             `json:"updatedAt"`
}

type DraftReviewCommentInput struct {
	ThreadID   *string            `json:"threadId,omitempty"`
	Path       string             `json:"path"`
	ViewerKind *string            `json:"viewerKind,omitempty"`
	Anchor     map[string]any     `json:"anchor"`
	Body       string             `json:"body"`
	Actor      *CommentActorInput `json:"actor,omitempty"`
	Author     *string            `json:"author,omitempty"`
	Source     *CommentSource     `json:"source,omitempty"`
}

type DraftReviewCommentUpdateInput struct {
	Body string `json:"body"`
}

type FileContext struct {
	File           *workspace.FilePayload `json:"file"`
	Comments       []*Comment             `json:"comments"`
	CommentThreads []*CommentThread       `json:"commentThreads"`
	Diff           *gitreview.TextDiff    `json:"diff,omitempty"`
}

type FsNode struct {
	ID             string    `json:"id"`
	Path           string    `json:"path"`
	Name           string    `json:"name"`
	Kind           NodeKind  `json:"kind"`
	ParentPath     *string   `json:"parentPath,omitempty"`
	ViewerKind     *string   `json:"viewerKind,omitempty"`
	Children       []*FsNode `json:"children,omitempty"`
	ChildrenLoaded *bool     `json:"childrenLoaded,omitempty"`
	Size           *int      `json:"size,omitempty"`
	MtimeMs        *float64  `json:"mtimeMs,omitempty"`
	Version        *int      `json:"version,omitempty"`
}

type Meta struct {
	Version  string       `json:"version"`
	Comments *CommentMeta `json:"comments"`
}

type Mutation struct {
}

type PreviewResource struct {
	URL            string  `json:"url"`
	ContentType    *string `json:"contentType,omitempty"`
	ScriptsAllowed bool    `json:"scriptsAllowed"`
	Transport      string  `json:"transport"`
}

type PublishDraftReviewCommentsInput struct {
	DraftIds []string           `json:"draftIds,omitempty"`
	Actor    *CommentActorInput `json:"actor,omitempty"`
}

type PublishedReviewBatch struct {
	ReviewBatchID string           `json:"reviewBatchId"`
	PublishedAt   string           `json:"publishedAt"`
	Threads       []*CommentThread `json:"threads"`
}

type Query struct {
}

type Subscription struct {
}

type ViewerConfig struct {
	Root             string `json:"root"`
	AllowHTMLScripts bool   `json:"allowHtmlScripts"`
	MaxFileSizeBytes int    `json:"maxFileSizeBytes"`
}

type Workspace struct {
	Tree   *workspace.TreeSnapshot `json:"tree"`
	Config *ViewerConfig           `json:"config"`
}

type WorkspaceEvent struct {
	Type    string    `json:"type"`
	Path    string    `json:"path"`
	Kind    *NodeKind `json:"kind,omitempty"`
	Version int       `json:"version"`
}

type CommentActorKind string

const (
	CommentActorKindHuman      CommentActorKind = "human"
	CommentActorKindClaudeCode CommentActorKind = "claude_code"
	CommentActorKindCodex      CommentActorKind = "codex"
	CommentActorKindUnknown    CommentActorKind = "unknown"
)

var AllCommentActorKind = []CommentActorKind{
	CommentActorKindHuman,
	CommentActorKindClaudeCode,
	CommentActorKindCodex,
	CommentActorKindUnknown,
}

func (e CommentActorKind) IsValid() bool {
	switch e {
	case CommentActorKindHuman, CommentActorKindClaudeCode, CommentActorKindCodex, CommentActorKindUnknown:
		return true
	}
	return false
}

func (e CommentActorKind) String() string {
	return string(e)
}

func (e *CommentActorKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentActorKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentActorKind", str)
	}
	return nil
}

func (e CommentActorKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentActorKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentActorKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentExportFormat string

const (
	CommentExportFormatJsonl CommentExportFormat = "jsonl"
)

var AllCommentExportFormat = []CommentExportFormat{
	CommentExportFormatJsonl,
}

func (e CommentExportFormat) IsValid() bool {
	switch e {
	case CommentExportFormatJsonl:
		return true
	}
	return false
}

func (e CommentExportFormat) String() string {
	return string(e)
}

func (e *CommentExportFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentExportFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentExportFormat", str)
	}
	return nil
}

func (e CommentExportFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentExportFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentExportFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentSource string

const (
	CommentSourceHuman      CommentSource = "human"
	CommentSourceClaudeCode CommentSource = "claude_code"
	CommentSourceCodex      CommentSource = "codex"
	CommentSourceUnknown    CommentSource = "unknown"
)

var AllCommentSource = []CommentSource{
	CommentSourceHuman,
	CommentSourceClaudeCode,
	CommentSourceCodex,
	CommentSourceUnknown,
}

func (e CommentSource) IsValid() bool {
	switch e {
	case CommentSourceHuman, CommentSourceClaudeCode, CommentSourceCodex, CommentSourceUnknown:
		return true
	}
	return false
}

func (e CommentSource) String() string {
	return string(e)
}

func (e *CommentSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentSource", str)
	}
	return nil
}

func (e CommentSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentStatus string

const (
	CommentStatusOpen     CommentStatus = "open"
	CommentStatusResolved CommentStatus = "resolved"
	CommentStatusArchived CommentStatus = "archived"
)

var AllCommentStatus = []CommentStatus{
	CommentStatusOpen,
	CommentStatusResolved,
	CommentStatusArchived,
}

func (e CommentStatus) IsValid() bool {
	switch e {
	case CommentStatusOpen, CommentStatusResolved, CommentStatusArchived:
		return true
	}
	return false
}

func (e CommentStatus) String() string {
	return string(e)
}

func (e *CommentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentStatus", str)
	}
	return nil
}

func (e CommentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentThreadActivityType string

const (
	CommentThreadActivityTypeThreadCreated       CommentThreadActivityType = "thread_created"
	CommentThreadActivityTypeThreadRead          CommentThreadActivityType = "thread_read"
	CommentThreadActivityTypeCommentAdded        CommentThreadActivityType = "comment_added"
	CommentThreadActivityTypeCommentUpdated      CommentThreadActivityType = "comment_updated"
	CommentThreadActivityTypeThreadStatusChanged CommentThreadActivityType = "thread_status_changed"
	CommentThreadActivityTypeThreadClaimed       CommentThreadActivityType = "thread_claimed"
	CommentThreadActivityTypeThreadClaimReleased CommentThreadActivityType = "thread_claim_released"
)

var AllCommentThreadActivityType = []CommentThreadActivityType{
	CommentThreadActivityTypeThreadCreated,
	CommentThreadActivityTypeThreadRead,
	CommentThreadActivityTypeCommentAdded,
	CommentThreadActivityTypeCommentUpdated,
	CommentThreadActivityTypeThreadStatusChanged,
	CommentThreadActivityTypeThreadClaimed,
	CommentThreadActivityTypeThreadClaimReleased,
}

func (e CommentThreadActivityType) IsValid() bool {
	switch e {
	case CommentThreadActivityTypeThreadCreated, CommentThreadActivityTypeThreadRead, CommentThreadActivityTypeCommentAdded, CommentThreadActivityTypeCommentUpdated, CommentThreadActivityTypeThreadStatusChanged, CommentThreadActivityTypeThreadClaimed, CommentThreadActivityTypeThreadClaimReleased:
		return true
	}
	return false
}

func (e CommentThreadActivityType) String() string {
	return string(e)
}

func (e *CommentThreadActivityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentThreadActivityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentThreadActivityType", str)
	}
	return nil
}

func (e CommentThreadActivityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentThreadActivityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentThreadActivityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DiffSide string

const (
	DiffSideOld DiffSide = "old"
	DiffSideNew DiffSide = "new"
)

var AllDiffSide = []DiffSide{
	DiffSideOld,
	DiffSideNew,
}

func (e DiffSide) IsValid() bool {
	switch e {
	case DiffSideOld, DiffSideNew:
		return true
	}
	return false
}

func (e DiffSide) String() string {
	return string(e)
}

func (e *DiffSide) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiffSide(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiffSide", str)
	}
	return nil
}

func (e DiffSide) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DiffSide) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DiffSide) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeKind string

const (
	NodeKindFile      NodeKind = "file"
	NodeKindDirectory NodeKind = "directory"
)

var AllNodeKind = []NodeKind{
	NodeKindFile,
	NodeKindDirectory,
}

func (e NodeKind) IsValid() bool {
	switch e {
	case NodeKindFile, NodeKindDirectory:
		return true
	}
	return false
}

func (e NodeKind) String() string {
	return string(e)
}

func (e *NodeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeKind", str)
	}
	return nil
}

func (e NodeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
