// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/tasuku43/vivi/server/gitreview"
	"github.com/tasuku43/vivi/server/workspace"
)

type ChangeReviewSummary struct {
	Available bool                `json:"available"`
	Reason    *string             `json:"reason,omitempty"`
	Changes   []*gitreview.Change `json:"changes"`
}

type Comment struct {
	ID         string         `json:"id"`
	ThreadID   *string        `json:"threadId,omitempty"`
	Path       string         `json:"path"`
	ViewerKind string         `json:"viewerKind"`
	Anchor     map[string]any `json:"anchor"`
	Body       string         `json:"body"`
	Status     CommentStatus  `json:"status"`
	CreatedAt  string         `json:"createdAt"`
	UpdatedAt  string         `json:"updatedAt"`
	ResolvedAt *string        `json:"resolvedAt,omitempty"`
	ArchivedAt *string        `json:"archivedAt,omitempty"`
}

type CommentExport struct {
	Format      CommentExportFormat `json:"format"`
	ContentType string              `json:"contentType"`
	Content     string              `json:"content"`
}

type CommentInput struct {
	ThreadID   *string        `json:"threadId,omitempty"`
	Path       string         `json:"path"`
	ViewerKind *string        `json:"viewerKind,omitempty"`
	Anchor     map[string]any `json:"anchor"`
	Body       string         `json:"body"`
	Status     *CommentStatus `json:"status,omitempty"`
}

type CommentMeta struct {
	Statuses      []CommentStatus `json:"statuses"`
	Surfaces      []string        `json:"surfaces"`
	ExportFormats []string        `json:"exportFormats"`
}

type CommentThread struct {
	ID        string         `json:"id"`
	Path      string         `json:"path"`
	Status    CommentStatus  `json:"status"`
	Anchor    map[string]any `json:"anchor,omitempty"`
	UpdatedAt *string        `json:"updatedAt,omitempty"`
	Comments  []*Comment     `json:"comments"`
}

type CommentThreadUpdateInput struct {
	Status CommentStatus `json:"status"`
}

type CommentUpdateInput struct {
	Body   *string        `json:"body,omitempty"`
	Status *CommentStatus `json:"status,omitempty"`
}

type FileContext struct {
	File           *workspace.FilePayload `json:"file"`
	Comments       []*Comment             `json:"comments"`
	CommentThreads []*CommentThread       `json:"commentThreads"`
	Diff           *gitreview.TextDiff    `json:"diff,omitempty"`
}

type FsNode struct {
	ID             string    `json:"id"`
	Path           string    `json:"path"`
	Name           string    `json:"name"`
	Kind           NodeKind  `json:"kind"`
	ParentPath     *string   `json:"parentPath,omitempty"`
	ViewerKind     *string   `json:"viewerKind,omitempty"`
	Children       []*FsNode `json:"children,omitempty"`
	ChildrenLoaded *bool     `json:"childrenLoaded,omitempty"`
	Size           *int      `json:"size,omitempty"`
	MtimeMs        *float64  `json:"mtimeMs,omitempty"`
	Version        *int      `json:"version,omitempty"`
}

type Meta struct {
	Version  string       `json:"version"`
	Comments *CommentMeta `json:"comments"`
}

type Mutation struct {
}

type PreviewResource struct {
	URL            string  `json:"url"`
	ContentType    *string `json:"contentType,omitempty"`
	ScriptsAllowed bool    `json:"scriptsAllowed"`
	Transport      string  `json:"transport"`
}

type Query struct {
}

type Subscription struct {
}

type ViewerConfig struct {
	Root             string `json:"root"`
	AllowHTMLScripts bool   `json:"allowHtmlScripts"`
	MaxFileSizeBytes int    `json:"maxFileSizeBytes"`
}

type Workspace struct {
	Tree   *workspace.TreeSnapshot `json:"tree"`
	Config *ViewerConfig           `json:"config"`
}

type WorkspaceEvent struct {
	Type    string    `json:"type"`
	Path    string    `json:"path"`
	Kind    *NodeKind `json:"kind,omitempty"`
	Version int       `json:"version"`
}

type CommentExportFormat string

const (
	CommentExportFormatJsonl CommentExportFormat = "jsonl"
)

var AllCommentExportFormat = []CommentExportFormat{
	CommentExportFormatJsonl,
}

func (e CommentExportFormat) IsValid() bool {
	switch e {
	case CommentExportFormatJsonl:
		return true
	}
	return false
}

func (e CommentExportFormat) String() string {
	return string(e)
}

func (e *CommentExportFormat) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentExportFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentExportFormat", str)
	}
	return nil
}

func (e CommentExportFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentExportFormat) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentExportFormat) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentStatus string

const (
	CommentStatusOpen     CommentStatus = "open"
	CommentStatusResolved CommentStatus = "resolved"
	CommentStatusArchived CommentStatus = "archived"
)

var AllCommentStatus = []CommentStatus{
	CommentStatusOpen,
	CommentStatusResolved,
	CommentStatusArchived,
}

func (e CommentStatus) IsValid() bool {
	switch e {
	case CommentStatusOpen, CommentStatusResolved, CommentStatusArchived:
		return true
	}
	return false
}

func (e CommentStatus) String() string {
	return string(e)
}

func (e *CommentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentStatus", str)
	}
	return nil
}

func (e CommentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type NodeKind string

const (
	NodeKindFile      NodeKind = "file"
	NodeKindDirectory NodeKind = "directory"
)

var AllNodeKind = []NodeKind{
	NodeKindFile,
	NodeKindDirectory,
}

func (e NodeKind) IsValid() bool {
	switch e {
	case NodeKindFile, NodeKindDirectory:
		return true
	}
	return false
}

func (e NodeKind) String() string {
	return string(e)
}

func (e *NodeKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeKind", str)
	}
	return nil
}

func (e NodeKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
