package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"

	"github.com/tasuku43/vivi/server/application"
	"github.com/tasuku43/vivi/server/comments"
	"github.com/tasuku43/vivi/server/gitreview"
	"github.com/tasuku43/vivi/server/graphql/generated"
	"github.com/tasuku43/vivi/server/graphql/model"
	"github.com/tasuku43/vivi/server/workspace"
)

// CreateThread is the resolver for the createThread field.
func (r *mutationResolver) CreateThread(ctx context.Context, input model.CommentInput) (*model.CommentThread, error) {
	thread, err := r.service.CreateCommentThread(commentInputMap(input))
	if err != nil {
		return nil, err
	}
	return commentThreadsFromDomain([]application.CommentThread{thread})[0], nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, threadID string, input model.AddCommentInput) (*model.Comment, error) {
	comment, err := r.service.AddComment(threadID, addCommentInputMap(input))
	if err != nil {
		return nil, err
	}
	return commentFromMap(comment), nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CommentInput) (*model.Comment, error) {
	comment, err := r.service.CreateComment(commentInputMap(input))
	if err != nil {
		return nil, err
	}
	return commentFromMap(comment), nil
}

// CreateDraftReviewComment is the resolver for the createDraftReviewComment field.
func (r *mutationResolver) CreateDraftReviewComment(ctx context.Context, input model.DraftReviewCommentInput) (*model.DraftReviewComment, error) {
	draft, err := r.service.CreateDraftReviewComment(draftReviewCommentInputMap(input))
	if err != nil {
		return nil, err
	}
	return draftReviewCommentFromMap(draft), nil
}

// UpdateDraftReviewComment is the resolver for the updateDraftReviewComment field.
func (r *mutationResolver) UpdateDraftReviewComment(ctx context.Context, id string, input model.DraftReviewCommentUpdateInput) (*model.DraftReviewComment, error) {
	draft, err := r.service.UpdateDraftReviewComment(id, map[string]any{"body": input.Body})
	if err != nil {
		return nil, err
	}
	return draftReviewCommentFromMap(draft), nil
}

// DeleteDraftReviewComment is the resolver for the deleteDraftReviewComment field.
func (r *mutationResolver) DeleteDraftReviewComment(ctx context.Context, id string) (*model.DraftReviewComment, error) {
	draft, err := r.service.DeleteDraftReviewComment(id)
	if err != nil {
		return nil, err
	}
	return draftReviewCommentFromMap(draft), nil
}

// PublishDraftReviewComments is the resolver for the publishDraftReviewComments field.
func (r *mutationResolver) PublishDraftReviewComments(ctx context.Context, input *model.PublishDraftReviewCommentsInput) (*model.PublishedReviewBatch, error) {
	draftIDs := []string{}
	actor := map[string]any{"id": "unknown", "kind": "unknown"}
	if input != nil {
		draftIDs = input.DraftIds
		actor = commentActorInputMap(input.Actor)
	}
	batch, err := r.service.PublishDraftReviewComments(draftIDs, actor)
	if err != nil {
		return nil, err
	}
	return publishedReviewBatchFromMap(batch), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, input model.CommentUpdateInput) (*model.Comment, error) {
	comment, err := r.service.UpdateComment(id, commentUpdateInputMap(input))
	if err != nil {
		return nil, err
	}
	return commentFromMap(comment), nil
}

// ResolveThread is the resolver for the resolveThread field.
func (r *mutationResolver) ResolveThread(ctx context.Context, id string, actor *model.CommentActorInput) (*model.CommentThread, error) {
	thread, err := r.service.ResolveCommentThread(id, commentActorInputMap(actor))
	if err != nil {
		return nil, err
	}
	return commentThreadsFromDomain([]application.CommentThread{thread})[0], nil
}

// ArchiveThread is the resolver for the archiveThread field.
func (r *mutationResolver) ArchiveThread(ctx context.Context, id string, actor *model.CommentActorInput) (*model.CommentThread, error) {
	thread, err := r.service.ArchiveCommentThread(id, commentActorInputMap(actor))
	if err != nil {
		return nil, err
	}
	return commentThreadsFromDomain([]application.CommentThread{thread})[0], nil
}

// ReopenThread is the resolver for the reopenThread field.
func (r *mutationResolver) ReopenThread(ctx context.Context, id string, actor *model.CommentActorInput) (*model.CommentThread, error) {
	thread, err := r.service.ReopenCommentThread(id, commentActorInputMap(actor))
	if err != nil {
		return nil, err
	}
	return commentThreadsFromDomain([]application.CommentThread{thread})[0], nil
}

// UpdateCommentThread is the resolver for the updateCommentThread field.
func (r *mutationResolver) UpdateCommentThread(ctx context.Context, id string, input model.CommentThreadUpdateInput) (*model.CommentThread, error) {
	thread, err := r.service.UpdateCommentThread(id, map[string]any{"status": input.Status.String(), "actor": commentActorInputMap(input.Actor)})
	if err != nil {
		return nil, err
	}
	return commentThreadsFromDomain([]application.CommentThread{thread})[0], nil
}

// Workspace is the resolver for the workspace field.
func (r *queryResolver) Workspace(ctx context.Context, path *string, depth *int) (*model.Workspace, error) {
	tree, err := r.Tree(ctx, path, depth)
	if err != nil {
		return nil, err
	}
	return &model.Workspace{
		Tree:   tree,
		Config: viewerConfigFromDomain(r.service.Config()),
	}, nil
}

// Config is the resolver for the config field.
func (r *queryResolver) Config(ctx context.Context) (*model.ViewerConfig, error) {
	return viewerConfigFromDomain(r.service.Config()), nil
}

// Tree is the resolver for the tree field.
func (r *queryResolver) Tree(ctx context.Context, path *string, depth *int) (*workspace.TreeSnapshot, error) {
	pathValue := ""
	if path != nil {
		pathValue = *path
	}
	depthValue := 0
	if depth != nil {
		depthValue = *depth
	}
	tree, err := r.service.ReadTree(pathValue, depthValue)
	if err != nil {
		return nil, err
	}
	return &tree, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, path string) (*workspace.FilePayload, error) {
	file, err := r.service.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return &file, nil
}

// FileContext is the resolver for the fileContext field.
func (r *queryResolver) FileContext(ctx context.Context, path string, includeComments *bool, includeDiff *bool, diffBase *string) (*model.FileContext, error) {
	file, err := r.service.ReadFile(path)
	if err != nil {
		return nil, err
	}
	result := &model.FileContext{
		File:           &file,
		Comments:       []*model.Comment{},
		CommentThreads: []*model.CommentThread{},
	}
	if includeComments != nil && *includeComments {
		items, err := r.service.ListComments(comments.Filters{Path: path})
		if err != nil {
			return nil, err
		}
		result.Comments = commentsFromMaps(items)
		threads, err := r.service.ListCommentThreads(comments.Filters{Path: path})
		if err != nil {
			return nil, err
		}
		application.ObserveThreadReads(ctx, threadIDsFromDomain(threads))
		result.CommentThreads = commentThreadsFromDomain(threads)
	}
	if includeDiff != nil && *includeDiff {
		base := ""
		if diffBase != nil {
			base = *diffBase
		}
		diff := r.service.ReadDiff(ctx, path, base)
		result.Diff = &diff
	}
	return result, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, path *string, status *model.CommentStatus) ([]*model.Comment, error) {
	pathValue, statusValue := commentFilters(path, status)
	items, err := r.service.ListComments(comments.Filters{Path: pathValue, Status: statusValue})
	if err != nil {
		return nil, err
	}
	application.ObserveThreadReads(ctx, threadIDsFromCommentMaps(items))
	return commentsFromMaps(items), nil
}

// CommentThreads is the resolver for the commentThreads field.
func (r *queryResolver) CommentThreads(ctx context.Context, path *string, status *model.CommentStatus) ([]*model.CommentThread, error) {
	pathValue, statusValue := commentFilters(path, status)
	items, err := r.service.ListCommentThreads(comments.Filters{Path: pathValue, Status: statusValue})
	if err != nil {
		return nil, err
	}
	application.ObserveThreadReads(ctx, threadIDsFromDomain(items))
	return commentThreadsFromDomain(items), nil
}

// DraftReviewComments is the resolver for the draftReviewComments field.
func (r *queryResolver) DraftReviewComments(ctx context.Context, path *string) ([]*model.DraftReviewComment, error) {
	pathValue := ""
	if path != nil {
		pathValue = *path
	}
	items, err := r.service.ListDraftReviewComments(comments.Filters{Path: pathValue})
	if err != nil {
		return nil, err
	}
	return draftReviewCommentsFromMaps(items), nil
}

// CommentThreadActivities is the resolver for the commentThreadActivities field.
func (r *queryResolver) CommentThreadActivities(ctx context.Context, threadID string, after *string, first *int) ([]*model.CommentThreadActivityEvent, error) {
	firstValue := 100
	if first != nil {
		firstValue = *first
	}
	items, err := r.service.ListCommentThreadActivities(threadID, stringPointerValue(after), firstValue)
	if err != nil {
		return nil, err
	}
	return activitiesFromMaps(items), nil
}

// CommentExport is the resolver for the commentExport field.
func (r *queryResolver) CommentExport(ctx context.Context, path *string, status *model.CommentStatus, format *model.CommentExportFormat) (*model.CommentExport, error) {
	_ = format
	pathValue, statusValue := commentFilters(path, status)
	content, err := r.service.ExportCommentsJSONL(comments.Filters{Path: pathValue, Status: statusValue})
	if err != nil {
		return nil, err
	}
	return &model.CommentExport{
		Format:      model.CommentExportFormatJsonl,
		ContentType: "application/x-ndjson; charset=utf-8",
		Content:     content,
	}, nil
}

// ReviewQueue is the resolver for the reviewQueue field.
func (r *queryResolver) ReviewQueue(ctx context.Context) (*model.ChangeReviewSummary, error) {
	return reviewSummaryFromDomain(r.service.ReadChanges(ctx)), nil
}

// DiffBases is the resolver for the diffBases field.
func (r *queryResolver) DiffBases(ctx context.Context) (*gitreview.DiffBaseSummary, error) {
	result := r.service.ReadDiffBases(ctx)
	return &result, nil
}

// Diff is the resolver for the diff field.
func (r *queryResolver) Diff(ctx context.Context, path string, base *string) (*gitreview.TextDiff, error) {
	baseValue := ""
	if base != nil {
		baseValue = *base
	}
	result := r.service.ReadDiff(ctx, path, baseValue)
	return &result, nil
}

// FileSearch is the resolver for the fileSearch field.
func (r *queryResolver) FileSearch(ctx context.Context, query string, limit *int) (*workspace.FileSearchResponse, error) {
	limitValue := 0
	if limit != nil {
		limitValue = *limit
	}
	result, err := r.service.SearchFiles(query, limitValue)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// TextSearch is the resolver for the textSearch field.
func (r *queryResolver) TextSearch(ctx context.Context, query string, limit *int) (*workspace.TextSearchResponse, error) {
	limitValue := 0
	if limit != nil {
		limitValue = *limit
	}
	result, err := r.service.SearchText(query, limitValue)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Meta is the resolver for the meta field.
func (r *queryResolver) Meta(ctx context.Context) (*model.Meta, error) {
	return &model.Meta{
		Version: "v1",
		Comments: &model.CommentMeta{
			Statuses:      []model.CommentStatus{model.CommentStatusOpen, model.CommentStatusResolved, model.CommentStatusArchived},
			Surfaces:      []string{"source", "rendered", "diff"},
			ExportFormats: []string{"jsonl"},
			ActorKinds:    model.AllCommentActorKind,
			ActivityTypes: model.AllCommentThreadActivityType,
		},
	}, nil
}

// HTMLPreview is the resolver for the htmlPreview field.
func (r *queryResolver) HTMLPreview(ctx context.Context, path string) (*model.PreviewResource, error) {
	return &model.PreviewResource{
		URL:            "/preview/html?path=" + path,
		ScriptsAllowed: r.service.Config().AllowHTMLScripts,
		Transport:      "http-rendering",
	}, nil
}

// RawPreview is the resolver for the rawPreview field.
func (r *queryResolver) RawPreview(ctx context.Context, path string) (*model.PreviewResource, error) {
	return &model.PreviewResource{
		URL:            "/preview/raw/" + path,
		ScriptsAllowed: false,
		Transport:      "http-rendering",
	}, nil
}

// WorkspaceEvents is the resolver for the workspaceEvents field.
func (r *subscriptionResolver) WorkspaceEvents(ctx context.Context) (<-chan *model.WorkspaceEvent, error) {
	events := make(chan *model.WorkspaceEvent)
	source, unsubscribe := r.service.SubscribeWorkspaceEvents()
	go func() {
		defer close(events)
		defer unsubscribe()
		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-source:
				if !ok {
					return
				}
				select {
				case events <- workspaceEventFromDomain(event):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return events, nil
}

// CommentThreadActivity is the resolver for the commentThreadActivity field.
func (r *subscriptionResolver) CommentThreadActivity(ctx context.Context, threadID *string) (<-chan *model.CommentThreadActivityEvent, error) {
	source, unsubscribe := r.service.SubscribeCommentThreadActivities()
	events := make(chan *model.CommentThreadActivityEvent, 32)
	go func() {
		defer close(events)
		defer unsubscribe()
		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-source:
				if !ok {
					return
				}
				if threadID != nil && *threadID != stringValue(event["threadId"]) {
					continue
				}
				select {
				case events <- activityFromMap(event):
				case <-ctx.Done():
					return
				}
			}
		}
	}()
	return events, nil
}

// Nodes is the resolver for the nodes field.
func (r *treeSnapshotResolver) Nodes(ctx context.Context, obj *workspace.TreeSnapshot) ([]*model.FsNode, error) {
	return nodesFromDomain(obj.Nodes), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

// TreeSnapshot returns generated.TreeSnapshotResolver implementation.
func (r *Resolver) TreeSnapshot() generated.TreeSnapshotResolver { return &treeSnapshotResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type treeSnapshotResolver struct{ *Resolver }
